# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhoneService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PhoneService.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12PhoneService.proto\x12\x04grpc\"+\n\x0cPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"6\n\rPhoneResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t2E\n\x0cPhoneService\x12\x35\n\ncheckPhone\x12\x12.grpc.PhoneRequest\x1a\x13.grpc.PhoneResponseb\x06proto3'
)




_PHONEREQUEST = _descriptor.Descriptor(
  name='PhoneRequest',
  full_name='grpc.PhoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='grpc.PhoneRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='grpc.PhoneRequest.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=71,
)


_PHONERESPONSE = _descriptor.Descriptor(
  name='PhoneResponse',
  full_name='grpc.PhoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='grpc.PhoneResponse.responseCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.PhoneResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['PhoneRequest'] = _PHONEREQUEST
DESCRIPTOR.message_types_by_name['PhoneResponse'] = _PHONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneRequest = _reflection.GeneratedProtocolMessageType('PhoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHONEREQUEST,
  '__module__' : 'PhoneService_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PhoneRequest)
  })
_sym_db.RegisterMessage(PhoneRequest)

PhoneResponse = _reflection.GeneratedProtocolMessageType('PhoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _PHONERESPONSE,
  '__module__' : 'PhoneService_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PhoneResponse)
  })
_sym_db.RegisterMessage(PhoneResponse)



_PHONESERVICE = _descriptor.ServiceDescriptor(
  name='PhoneService',
  full_name='grpc.PhoneService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='checkPhone',
    full_name='grpc.PhoneService.checkPhone',
    index=0,
    containing_service=None,
    input_type=_PHONEREQUEST,
    output_type=_PHONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PHONESERVICE)

DESCRIPTOR.services_by_name['PhoneService'] = _PHONESERVICE

# @@protoc_insertion_point(module_scope)
