# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PhoneService_pb2 as PhoneService__pb2


class PhoneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkPhone = channel.unary_unary(
                '/grpc.PhoneService/checkPhone',
                request_serializer=PhoneService__pb2.PhoneRequest.SerializeToString,
                response_deserializer=PhoneService__pb2.PhoneResponse.FromString,
                )


class PhoneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhoneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.checkPhone,
                    request_deserializer=PhoneService__pb2.PhoneRequest.FromString,
                    response_serializer=PhoneService__pb2.PhoneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.PhoneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhoneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.PhoneService/checkPhone',
            PhoneService__pb2.PhoneRequest.SerializeToString,
            PhoneService__pb2.PhoneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
